-- Pendenzenliste -- Supabase-Schema (Postgres). Portierung von backend/src/schema.sql.
--
-- Handgepflegt und idempotent (kein Migrations-Tool), gleiches Muster wie im Schwesterprojekt
-- "CrossFit Tracker" (supabase/schema.sql). Einmal im Supabase SQL-Editor ausfuehren; danach
-- bei Aenderungen erneut ausfuehren (CREATE ... IF NOT EXISTS / CREATE OR REPLACE ueberall).
--
-- WICHTIGE ABWEICHUNG vom CrossFit-Tracker-Vorbild: das dort verwendete RLS-Muster
-- "auth.uid() = user_id" (jede Person sieht nur eigene Zeilen) passt hier NICHT -- die
-- Pendenzenliste ist eine Team-App, alle angemeldeten Mitarbeitenden teilen sich dieselben
-- Mandanten/Pendenzen. Policies unten pruefen darum nur "ist ueberhaupt angemeldet"
-- (auth.uid() is not null), nicht eine Zeilen-Eigentuemerschaft.

-- ==========================================================================
-- mitarbeitende -- eigene ID (nicht an auth.users gebunden), mit OPTIONALER Verknuepfung zu
-- einem Login-Konto. Anders als beim ersten Entwurf bewusst NICHT id = auth.users.id: die
-- bisherige App erlaubt Mitarbeitende OHNE Login (nur als Bearbeiter/in zuweisbar, siehe
-- Team.jsx "kein Login"-Tag) -- das bleibt so moeglich. Ersetzt die bisherige eigene
-- Session-/Passwort-Verwaltung (sitzungen, passwort_hash) durch Supabase Auth, aber nur fuer
-- Personen, die tatsaechlich ein Login-Konto bekommen.
-- ==========================================================================

create table if not exists public.mitarbeitende (
  id            bigint generated always as identity primary key,
  auth_user_id  uuid unique references auth.users(id) on delete set null,
  name          text not null,
  email         text,
  aktiv         boolean not null default true
);

-- Legt bei jeder neuen Supabase-Auth-Anmeldung (nur ueber Dashboard/Admin-API erzeugt, siehe
-- Migrationsplan Phase 2 -- keine oeffentliche Selbstregistrierung) die Verknuepfung zur
-- passenden mitarbeitende-Zeile an: existiert bereits eine Zeile mit derselben E-Mail (z.B.
-- vorher ohne Login angelegt), wird NUR die Verknuepfung ergaenzt (kein Duplikat) -- das
-- entspricht dem bisherigen "Login-Passwort festlegen" fuer eine bestehende Person. Sonst wird
-- eine neue Zeile angelegt. "name" kommt aus den Auth-User-Metadaten (beim Anlegen im
-- Dashboard unter "User Metadata" als {"name": "Angelo"} mitgeben), fehlt es, wird die E-Mail
-- als Platzhalter verwendet.
create or replace function public.handle_new_user()
returns trigger as $$
begin
  update public.mitarbeitende set auth_user_id = new.id
    where email = new.email and auth_user_id is null;
  if not found then
    insert into public.mitarbeitende (auth_user_id, name, email)
    values (new.id, coalesce(new.raw_user_meta_data->>'name', new.email), new.email);
  end if;
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ==========================================================================
-- mandanten
-- ==========================================================================

create table if not exists public.mandanten (
  id                        bigint generated by default as identity primary key,
  name                      text not null,
  kuerzel                   text,
  email                     text,  -- Ansprechpartner/in, Standard beim E-Mail-Versand
  geschaeftsfuehrung_email  text,  -- nur bei Bedarf, muss beim Versand manuell gewaehlt werden
  aktiv                     boolean not null default true,
  notizen                   text
);

-- ==========================================================================
-- wiederkehr_regeln
-- ==========================================================================

create table if not exists public.wiederkehr_regeln (
  id                  bigint generated by default as identity primary key,
  titel_vorlage       text not null,
  mandant_id          bigint references public.mandanten(id) on delete set null,
  rhythmus            text not null check (rhythmus in ('monatlich', 'quartalsweise', 'halbjaehrlich', 'jaehrlich')),
  faelligkeit_typ     text not null,
  faelligkeit_config  jsonb not null default '{}'::jsonb,
  vorlauf_tage        integer not null default 0,
  aktiv               boolean not null default true
);

-- ==========================================================================
-- pendenzen
-- ==========================================================================

create table if not exists public.pendenzen (
  id                          bigint generated by default as identity primary key,
  titel                       text not null,
  mandant_id                  bigint references public.mandanten(id) on delete set null,
  beschreibung                text,
  faelligkeit                 date not null,
  prioritaet                  text not null default 'Mittel' check (prioritaet in ('Hoch', 'Mittel', 'Tief')),
  status                      text not null default 'Offen' check (status in ('Offen', 'In Arbeit', 'Warte auf Kunde', 'Warte intern', 'Erledigt')),
  aufwand_stunden             numeric,
  erstellt_am                 timestamptz not null default now(),
  erledigt_am                 date,
  warte_seit                  date,
  wiedervorlage                date,
  regel_id                    bigint references public.wiederkehr_regeln(id) on delete set null,
  perioden_schluessel         text,
  uebergeordnete_pendenz_id   bigint references public.pendenzen(id) on delete cascade,
  bearbeiter_id               bigint references public.mitarbeitende(id) on delete set null
);

-- Idempotenz: pro Regel und Periode darf nur eine Pendenz existieren (Regel-Generator).
create unique index if not exists idx_pendenzen_regel_periode
  on public.pendenzen (regel_id, perioden_schluessel);

create index if not exists idx_pendenzen_status on public.pendenzen (status);
create index if not exists idx_pendenzen_faelligkeit on public.pendenzen (faelligkeit);
create index if not exists idx_pendenzen_mandant on public.pendenzen (mandant_id);
create index if not exists idx_pendenzen_uebergeordnet on public.pendenzen (uebergeordnete_pendenz_id);

-- --------------------------------------------------------------------------
-- Status-Kaskade Haupt-/Teilaufgabe -- Portierung von
-- backend/src/routes/pendenzen.js (leiteHauptaufgabenStatusAb / kaskadiereAnTeilaufgaben /
-- synchronisiereVerknuepfteAufgaben). Verhalten bewusst 1:1 uebernommen, inkl. der
-- bestehenden Eigenheit, dass JEDES Speichern einer Hauptaufgabe (nicht nur ein echter
-- Statuswechsel) ihre Teilaufgaben auf Offen/Erledigt zurueckstellt -- so verhaelt sich die
-- App heute schon, das ist keine neue Verschaerfung durch die Migration.
-- --------------------------------------------------------------------------

create or replace function public.pendenzen_status_kaskade()
returns trigger as $$
declare
  teilaufgaben_gesamt    integer;
  teilaufgaben_erledigt  integer;
  teilaufgaben_offen     integer;
  abgeleiteter_status    text;
  ziel_status            text;
begin
  if new.uebergeordnete_pendenz_id is not null then
    -- Diese Zeile ist eine Teilaufgabe: Status der Hauptaufgabe aus allen Teilaufgaben ableiten.
    select count(*), count(*) filter (where status = 'Erledigt'), count(*) filter (where status = 'Offen')
      into teilaufgaben_gesamt, teilaufgaben_erledigt, teilaufgaben_offen
      from public.pendenzen
      where uebergeordnete_pendenz_id = new.uebergeordnete_pendenz_id;

    if teilaufgaben_gesamt > 0 then
      abgeleiteter_status := case
        when teilaufgaben_erledigt = teilaufgaben_gesamt then 'Erledigt'
        when teilaufgaben_offen = teilaufgaben_gesamt then 'Offen'
        else 'In Arbeit'
      end;

      update public.pendenzen
        set status = abgeleiteter_status,
            erledigt_am = case when abgeleiteter_status = 'Erledigt' then current_date else null end
        where id = new.uebergeordnete_pendenz_id
          and status is distinct from abgeleiteter_status;
    end if;
  else
    -- Diese Zeile ist eine Hauptaufgabe: Status an alle direkten Teilaufgaben weitergeben.
    ziel_status := case when new.status = 'Erledigt' then 'Erledigt' else 'Offen' end;
    update public.pendenzen
      set status = ziel_status,
          erledigt_am = case when ziel_status = 'Erledigt' then current_date else null end
      where uebergeordnete_pendenz_id = new.id;
  end if;

  return null; -- AFTER-Trigger, Rueckgabewert wird ignoriert.
end;
$$ language plpgsql;

drop trigger if exists trg_pendenzen_status_insert on public.pendenzen;
create trigger trg_pendenzen_status_insert
  after insert on public.pendenzen
  for each row execute procedure public.pendenzen_status_kaskade();

drop trigger if exists trg_pendenzen_status_update on public.pendenzen;
create trigger trg_pendenzen_status_update
  after update of status, titel, beschreibung, faelligkeit, prioritaet, mandant_id, bearbeiter_id, aufwand_stunden, warte_seit, wiedervorlage
  on public.pendenzen
  for each row execute procedure public.pendenzen_status_kaskade();

-- Wird eine Teilaufgabe geloescht, kann sich der abgeleitete Status der Hauptaufgabe aendern
-- (z.B. sind jetzt alle verbleibenden Teilaufgaben erledigt) -- Pendant zu
-- leiteHauptaufgabenStatusAb(...) im DELETE-Handler von routes/pendenzen.js.
create or replace function public.pendenzen_status_nach_loeschen()
returns trigger as $$
declare
  teilaufgaben_gesamt    integer;
  teilaufgaben_erledigt  integer;
  teilaufgaben_offen     integer;
  abgeleiteter_status    text;
begin
  if old.uebergeordnete_pendenz_id is not null then
    select count(*), count(*) filter (where status = 'Erledigt'), count(*) filter (where status = 'Offen')
      into teilaufgaben_gesamt, teilaufgaben_erledigt, teilaufgaben_offen
      from public.pendenzen
      where uebergeordnete_pendenz_id = old.uebergeordnete_pendenz_id;

    if teilaufgaben_gesamt > 0 then
      abgeleiteter_status := case
        when teilaufgaben_erledigt = teilaufgaben_gesamt then 'Erledigt'
        when teilaufgaben_offen = teilaufgaben_gesamt then 'Offen'
        else 'In Arbeit'
      end;

      update public.pendenzen
        set status = abgeleiteter_status,
            erledigt_am = case when abgeleiteter_status = 'Erledigt' then current_date else null end
        where id = old.uebergeordnete_pendenz_id
          and status is distinct from abgeleiteter_status;
    end if;
  end if;
  return null;
end;
$$ language plpgsql;

drop trigger if exists trg_pendenzen_status_delete on public.pendenzen;
create trigger trg_pendenzen_status_delete
  after delete on public.pendenzen
  for each row execute procedure public.pendenzen_status_nach_loeschen();

-- ==========================================================================
-- pendenz_emails / pendenz_notizen
-- ==========================================================================

create table if not exists public.pendenz_emails (
  id           bigint generated by default as identity primary key,
  pendenz_id   bigint not null references public.pendenzen(id) on delete cascade,
  an           text not null,
  betreff      text,
  gesendet_am  timestamptz not null default now()
);
create index if not exists idx_pendenz_emails_pendenz on public.pendenz_emails (pendenz_id);

create table if not exists public.pendenz_notizen (
  id              bigint generated by default as identity primary key,
  pendenz_id      bigint not null references public.pendenzen(id) on delete cascade,
  text            text not null,
  mitarbeiter_id  bigint references public.mitarbeitende(id) on delete set null,
  erstellt_am     timestamptz not null default now()
);
create index if not exists idx_pendenz_notizen_pendenz on public.pendenz_notizen (pendenz_id);

-- ==========================================================================
-- pendenzen_angereichert -- View mit denselben Zusatzspalten, die der bisherige Express-Server
-- bei jeder Liste immer mitgeliefert hat (TEILAUFGABEN_SPALTEN/EMAIL_SPALTEN in
-- backend/src/routes/pendenzen.js): Mandant-/Bearbeiter-Name, Teilaufgaben-Zaehler,
-- Hauptaufgaben-Titel (falls Teilaufgabe), E-Mail-Verlauf-Kurzinfo. Frontend liest ab jetzt aus
-- dieser View statt aus der rohen Tabelle. "security_invoker" sorgt dafuer, dass die View mit
-- den RLS-Rechten der ABFRAGENDEN Person laeuft, nicht denen der Besitzerin (sonst wuerde RLS
-- fuer diese View wirkungslos).
-- ==========================================================================

create or replace view public.pendenzen_angereichert
with (security_invoker = true) as
select
  p.*,
  m.name as mandant_name, m.kuerzel as mandant_kuerzel, m.email as mandant_email,
  m.geschaeftsfuehrung_email as mandant_geschaeftsfuehrung_email,
  b.name as bearbeiter_name, b.email as bearbeiter_email,
  (select count(*) from public.pendenzen c where c.uebergeordnete_pendenz_id = p.id) as teilaufgaben_gesamt,
  (select count(*) from public.pendenzen c where c.uebergeordnete_pendenz_id = p.id and c.status = 'Erledigt') as teilaufgaben_erledigt,
  eltern.titel as eltern_titel,
  (select count(*) from public.pendenz_emails e where e.pendenz_id = p.id) as email_anzahl,
  (select max(e.gesendet_am) from public.pendenz_emails e where e.pendenz_id = p.id) as email_zuletzt_gesendet_am
from public.pendenzen p
left join public.mandanten m on m.id = p.mandant_id
left join public.mitarbeitende b on b.id = p.bearbeiter_id
left join public.pendenzen eltern on eltern.id = p.uebergeordnete_pendenz_id;

-- ==========================================================================
-- Row Level Security -- Team-Zugriff: jede angemeldete Person (= jeder Eintrag in
-- mitarbeitende) darf alles lesen/schreiben. Es gibt keine oeffentliche Registrierung
-- (siehe handle_new_user oben + Migrationsplan Phase 2), darum reicht "angemeldet" als
-- Bedingung, ohne dass Fremde ueberhaupt ein Konto bekommen koennten.
-- ==========================================================================

alter table public.mitarbeitende    enable row level security;
alter table public.mandanten        enable row level security;
alter table public.wiederkehr_regeln enable row level security;
alter table public.pendenzen        enable row level security;
alter table public.pendenz_emails   enable row level security;
alter table public.pendenz_notizen  enable row level security;

drop policy if exists team_voller_zugriff on public.mitarbeitende;
create policy team_voller_zugriff on public.mitarbeitende
  for all using (auth.uid() is not null) with check (auth.uid() is not null);

drop policy if exists team_voller_zugriff on public.mandanten;
create policy team_voller_zugriff on public.mandanten
  for all using (auth.uid() is not null) with check (auth.uid() is not null);

drop policy if exists team_voller_zugriff on public.wiederkehr_regeln;
create policy team_voller_zugriff on public.wiederkehr_regeln
  for all using (auth.uid() is not null) with check (auth.uid() is not null);

drop policy if exists team_voller_zugriff on public.pendenzen;
create policy team_voller_zugriff on public.pendenzen
  for all using (auth.uid() is not null) with check (auth.uid() is not null);

drop policy if exists team_voller_zugriff on public.pendenz_emails;
create policy team_voller_zugriff on public.pendenz_emails
  for all using (auth.uid() is not null) with check (auth.uid() is not null);

drop policy if exists team_voller_zugriff on public.pendenz_notizen;
create policy team_voller_zugriff on public.pendenz_notizen
  for all using (auth.uid() is not null) with check (auth.uid() is not null);

-- ==========================================================================
-- Aggregat-Funktionen -- ersetzen GET /api/pendenzen/cockpit und
-- GET /api/mandanten/uebersicht (backend/src/routes/pendenzen.js bzw. mandanten.js).
-- Als RPC-Funktionen statt Views, damit sie ueber supabase.rpc(...) mit einem Aufruf
-- konsumierbar sind.
-- ==========================================================================

create or replace function public.cockpit_daten()
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'ueberfaellig', coalesce((
      select jsonb_agg(p order by p.faelligkeit asc)
      from public.pendenzen_angereichert p
      where p.status != 'Erledigt' and p.faelligkeit < current_date
    ), '[]'::jsonb),
    'heuteFaellig', coalesce((
      select jsonb_agg(p)
      from public.pendenzen_angereichert p
      where p.status != 'Erledigt' and p.faelligkeit = current_date
    ), '[]'::jsonb),
    'morgenFaellig', coalesce((
      select jsonb_agg(p)
      from public.pendenzen_angereichert p
      where p.status != 'Erledigt' and p.faelligkeit = current_date + 1
    ), '[]'::jsonb),
    'nachfassen', coalesce((
      select jsonb_agg(p order by p.wiedervorlage asc)
      from public.pendenzen_angereichert p
      where p.status = 'Warte auf Kunde' and p.wiedervorlage is not null and p.wiedervorlage <= current_date
    ), '[]'::jsonb)
  );
$$;

create or replace function public.mandanten_uebersicht()
returns table (
  id bigint, name text, kuerzel text, email text, geschaeftsfuehrung_email text,
  aktiv boolean, notizen text, offene_pendenzen bigint, ueberfaellige_pendenzen bigint
)
language sql
stable
as $$
  select m.id, m.name, m.kuerzel, m.email, m.geschaeftsfuehrung_email, m.aktiv, m.notizen,
    count(p.id) filter (where p.status != 'Erledigt') as offene_pendenzen,
    count(p.id) filter (where p.status != 'Erledigt' and p.faelligkeit < current_date) as ueberfaellige_pendenzen
  from public.mandanten m
  left join public.pendenzen p on p.mandant_id = m.id
  group by m.id
  order by m.name;
$$;
